image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Frontend
    command: |
      cd frontend
      npm install
      npm start
    init: |
      cd frontend
      npm install
  - name: Start Backend
    command: |
      cd backend
      python3 server.py
    init: |
      cd backend
      pip install -r requirements.txt

ports:
  - port: 5000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
